name: dcli_scripts
version: 3.3.0
description: A collection of cli scripts that do odd jobs for me.
repository: https://github.com/bsutton/dcli_scripts
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.3.1
  dcli: ^4.0.1-alpha.8
  dcli_core: ^4.0.1-alpha.8
  docker2: ^4.0.0
  path: ^1.8.2
  pub_release: ^10.0.1
  pubspec_manager: ^1.0.0-alpha.14
  settings_yaml: ^8.0.1
  uuid: ^4.0.0
  win32: ^4.1.4
dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.0.0
executables:
  add_gnome_launcher:
  artifactory:
  bobthefish:
  certbot_renew:
  clean:
  dcompress:
  dcopydir:
  denv:
  dfind:
  dmailhog:
  dnsflush:
  docker_dcli:
  docker_push:
  downit:
  dmysql:
  dpath:
  dport:
  dreplace:
  dsetver:
  dsort:
  dvirtualbox:
  dwc:
  dwhich:
  dzfs_clean:
  eclipse_launcher:
  find_old_dart_packages:
  find_text:
  gactivate:
  gitadd_team_to_repository:
  gitcreation_date:
  gitgc:
  gituncommited:
  gitsyncfork:
  gitupdate_remote:
  hexdump:
  hog:
  install_flutter:
  ipaddr:
  kill_tomcat:
  pub_get_all:
